id = "snowfall"
name = "Snowfall Theme"
version = "0.2.0"
schema_version = 1
authors = ["Freethinkel <freethinkel@gmail.com>"]
description = "❄️ Winter theme for Zed"
repository = "https://github.com/freethinkel/snowfall-zed"
